kind: Namespace
apiVersion: v1
metadata:
  name: mpasa
  labels:
    name: mpasa

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mpasa
  name: mpasa
spec:
  selector:
    matchLabels:
      app: mpasa
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mpasa
    spec:
      containers:
      - name: mpasa
        image: mpasa:0.1.0
        args: []
        ports:
          - name: http
            containerPort: 8000
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mpasa
  name: mpasa
  namespace: mpasa
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: mpasa

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: mpasa
  name: mpasa
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
      - mpasa.me
      secretName: mpasa-tls
  rules:
  - host: "mpasa.me"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mpasa
            port:
              name: http

